// ─────────────────────────────────────────────────────────────────────────────
// THIS FILE IS GENERATED BY THE FIREBASE CLI.
// You must replace this file with your own generated version.
//
// HOW TO GENERATE IT (takes ~5 minutes):
//
//  1. Install the Firebase CLI:
//       npm install -g firebase-tools
//
//  2. Install the FlutterFire CLI:
//       dart pub global activate flutterfire_cli
//
//  3. Log into Firebase:
//       firebase login
//
//  4. From your project root (where pubspec.yaml lives), run:
//       flutterfire configure
//
//     Select your Firebase project (or create a new one).
//     Select "android" (and "ios" if needed).
//     This will REPLACE this file with real values.
//
//  5. In the Firebase Console (console.firebase.google.com):
//     a) Go to Build → Authentication → Sign-in method
//        Enable "Email/Password"
//     b) Go to Build → Firestore Database
//        Create a database (start in test mode for development)
//     c) Add these Firestore security rules (in the Rules tab):
//
//        rules_version = '2';
//        service cloud.firestore {
//          match /databases/{database}/documents {
//            match /users/{uid} {
//              allow read: if request.auth != null;
//              allow write: if request.auth.uid == uid;
//            }
//            match /logs/{logId} {
//              allow read, write: if request.auth != null
//                && request.auth.uid == resource.data.uid;
//              allow read: if request.auth != null
//                && get(/databases/$(database)/documents/users/$(request.auth.uid)).data.role == 'admin';
//            }
//          }
//        }
//
//  6. To make yourself admin: in Firestore Console, open the "users" collection,
//     find your document, and manually set the "role" field to "admin".
//
// ─────────────────────────────────────────────────────────────────────────────

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) throw UnsupportedError('Web not configured.');
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError('Platform not configured.');
    }
  }

  // ── REPLACE THESE VALUES with output from: flutterfire configure ──────────

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3SRPELTDP5c9_RYVy60dOIht-nReYzSQ',
    appId: '1:529976788961:android:a08f153d13fdcb87bff4a0',
    messagingSenderId: '529976788961',
    projectId: 'omkar-project-6969',
    storageBucket: 'omkar-project-6969.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey:            'YOUR_IOS_API_KEY',
    appId:             'YOUR_IOS_APP_ID',
    messagingSenderId: 'YOUR_SENDER_ID',
    projectId:         'YOUR_PROJECT_ID',
    storageBucket:     'YOUR_PROJECT_ID.appspot.com',
    iosBundleId:       'com.example.myApp',
  );
}